### PR TITLE
 Another batch of fr_FR translations

### PR DESCRIPTION
**Pull request by edugas**

### CODE REVIEW

**Comment by vegu** [comment]
@edugas thanks!

**Comment by vegu** [comment]
@edugas i just double checked and in this pull request your files put the french strings into `msgid` instead of `msgstr`, how are you editing the files? In any case `msgid` needs to retain the english strings, and translations should go into the accompanying `msgstr`.

I have reverted your pull request for now.

**Comment by vegu** [comment]
@edugas i have added a few of the translations of this pull request. See e88acb7. However when i was looking to fix the msgids like i did with your other pull request i found a lot of stuff already translated, likely by @mageo - i have not included those since i wasn't sure which ones were more correct. Are you guys communicating currently? If not, its probably advisable :)

**Comment by mageo** [comment]
I see the problem with the translations of @edugas that have been done in the msgids, I can correct that.

Basically, I just finished what @edugas started. I only changed his translations when I thought I had a better one. But sure, feel free to contact me if you want to synchronize our efforts.

**Comment by vegu** [comment]
@mageo it's appreciated, i fixed a 
 bunch of the msgids from the earlier pull requests in https://github.com/peeringdb/peeringdb/commit/c765b3c10e162f747fe7164598cf3370745b9245 so please make sure you pull those in before going over it.

**Comment by edugas** [comment]
Thanks @mageo and @vegu... totally missed the msgstr.

**Pull request merged**
