### PR TITLE
Please upload JP po files of second revision on beta page.

### PR DESCRIPTION
**Pull request by mwtr**
I have checked Japanese page on beta page, and revised some words in po files.
I'd like you to upload po files again.
Thank you.

### CODE REVIEW

**Comment by mwtr** [comment]
@grizz Could you please confirm and upload updated po files as second revision on the beta PeeringDB website?

**Comment by vegu** [comment]
@mwtr Pull request merged, thanks for the updates.

They will likely go to beta at some point during the next release cycle, which is scheduled for the end of this month. I will update here when they do.

**Comment by mwtr** [comment]
Thank you for your confirming the updates. Looking forward to next release!

**Comment by vegu** [comment]
@mwtr your changes to japanese locale should now be available on https://beta.peeringdb.com

**Comment by mwtr** [comment]
@vegu Thank you for your updating locale file on beta website! Let me check! :)

**Pull request merged**
