### PR TITLE
User Profile: Sort language select input with user's locale

### PR DESCRIPTION
**Pull request by dvanallen**
Allows any select input to use a new `data-edit-sorted` attribute to indicate that the select options should be sorted by name, as represented in the user's currently-selected locale.

Updates the language selection drop-down in the User Profile settings to use this new attribute.

### CODE REVIEW

**Comment by dvanallen** [comment]
The languages are sorting and displaying correctly.  I'm able to change language preferences, and the languages are then translated and sorted/displayed correctly again.

English:

image

Change to French:
Screen Shot 2022-09-10 at 2 20 01 PM

**Comment by dvanallen** [comment]
Fixes #468

**Review by grizz — APPROVED** [review]

**Comment by grizz** [comment]
@dvanallen Looks great, thanks!

Did you see:

> This pull request **introduces 1 alert** when merging [b7a2bcd](https://github.com/peeringdb/peeringdb/commit/b7a2bcd8810f66a38da46d94897ac8002a90232e) into [2a2c1d3](https://github.com/peeringdb/peeringdb/commit/2a2c1d3f3bf16b73ee2caa165ae55f29cfa7f597) - [view on LGTM.com](https://lgtm.com/projects/g/peeringdb/peeringdb/rev/pr-81cc73c3c1a52b4639e9c9cf56f86b98633bf71d)
> 
> **new alerts:**
> 
> * 1 for Missing variable declaration

**Comment by dvanallen** [comment]
Yeah, the LGTM check failed on my original commit, but then I amended it with a fix, and it looks like the latest code is passing.  Let me know if I missed something!

**Comment by grizz** [comment]
Oh, right, I see that now, thanks!

**Review by vegu — APPROVED** [review]

**Pull request merged**
