### PR TITLE
Typos in locale

### LINKED ISSUE #321: Typos in locale
Found some typos in django.po:

1) %(user_name)s's **afilliation** request has been approved
2) %(user_name)s's **afilliation** request has been denied
3) **Sepcifies** whether an ixp is allowed to add a netixlan entry for this network via their ixp_member data
4) Object of type '%(type)s' cannot be created because **it's** parent entity '%(parent_tag)s/%(parent_id)s' has not yet been approved
5) Object of type '%(type)s' cannot be created because **it's** parent entity '%(parent_tag)s/%(parent_id)s' has been marked as deleted
6) Has this object's latitude and longitude been syncronized to **it's** address fields
7) The email confirmation process for this email address has been terminated, please **re-initate**
8) User '%(u_name)s' created Network %(n_name)s AS%(n_asn)s (%(n_id)s) under **organzation** %(o_name)s (%(o_id)s).
9) As the user's email address was **succesfully** matched against RiR entry data this network has skipped the verification queue.
10) There was no entry in our database that matches that ASN, so it is likely that a network and **organzation** for it will need to be created.
11) These are the website addresses were able to derive from the **organzation** and **it's** entities
12) Your affiliation request to the Organization '%(o_name)s' and **it's** entities has been approved.
13) This was the result of a manual review of your affiliation request to the organization or one of **it's** entities.
14) All merges are processed manually by peeringdb support staff. If you think this action has been executed in error please **dont** hesitate to contact peeringdb support at

1, 2) "afilliation" should be "affiliation"
3) "Sepcifies" should be "Specifies"
4, 5, 6, 11, 12, 13) "it's" should be "its"
7) "re-initate" should be "re-initiate"
8, 10, 11) "organzation" should be "organization"
9) "succesfully" should be "successfully"
14) "dont"should be "don't"

### PR DESCRIPTION
**Pull request by tbaschak**
This fixes #321

### CODE REVIEW

**Comment by ccaputo** [comment]
Some of these typo fixes are in migrations.  I am not sure it makes sense to fix typos there, rather than just in the resulting models/code.  @grizz?

**Comment by tbaschak** [comment]
I'm not super familiar with the code base, however I've made this all as individual commits so that commits can be cherry picked if need be (or squashed).

**Comment by grizz** [comment]
@ccaputo I was going to wait until after the next release in 2 weeks to attack this, but yes, you're correct. It doesn't hurt anything strictly speaking, but would be better to not touch migretions and do a new migration if we need to.

@tbaschak Thank you so much for the PR and you did a great job on doing single commits so we can cherry pick as needed, it just happened to land in the middle of a fairly major release, so give us a release cycle (generally 1 month) to pull all of this into the code base.

**Comment by grizz** [comment]
Merged in #842 since we had to fix a couple conflicts.

Thanks again @tbaschak -- good work!

**Pull request closed without merging**
