### PR TITLE
Completed to translate django.po to Japanese

### PR DESCRIPTION
**Pull request by mwtr**
Could you please upload files on beta site?

### CODE REVIEW

**Comment by vegu** [comment]
@mwtr thank you for your contributions!

**Comment by mwtr** [comment]
Thank you for your merging po files translated to Japanese into master.
Could you please tell us where I should check po files on bete site?

**Comment by grizz** [comment]
@mwtr PC hasn't planned the next beta rollout yet, we're going to discuss this week

**Comment by mwtr** [comment]
Thank you for your responding. We look forward to a good outcome of your discussion. :)

**Comment by mwtr** [comment]
@grizz -san,
If you have any updates about uploading po files on beta site, please let me know.

**Comment by vegu** [comment]
@mwtr we are planning to do a beta rollout either today (friday) or over the weekend

To be able to compile the messages files i had to do some changes, can you please have a look at https://github.com/peeringdb/peeringdb/commit/43e1c68a86b2a86e987810107ea92b7519080cd2 and review, thanks!

**Comment by mwtr** [comment]
@vegu  Thank you for your responding. Please let me check later.

**Comment by vegu** [comment]
@mwtr japanese locale has been deployed to beta

**Pull request merged**
